.define STACK_TOP 1fff

; assets
.define BG1_TILES_SIZE      01a0
.define BG2_TILES_SIZE      02e0
.define SPRITES_TILES_SIZE  0800
.define BG_PALETTES_SIZE      40
.define SPRITES_PALETTES_SIZE 40
.define BG2_MAP_SIZE        0700
.define BG_BUFFER_SIZE      0800
.define BG1_BUFFER_SIZE     1000

; game
.define SPAWN_PILLAR_DELAY    50 ; 80
.define PILLAR_SPACING        0a
.define PILLAR_HEIGHT       0017 ; 23
.define PILLAR_OPENING      0006
.define PILLAR_WRAP         0044
.define LEVEL_WIDTH8          46
.define LEVEL_WIDTH         0046 ; 70
.define LEVEL_HEIGHT        001c ; 28
.define BUFFER_WIDTH        0040 ; 64
.define FLAPPY_X              60
.define FLAPPY_X16          0060

; joypad
.define JOY_A       0080
.define JOY_AL        80
.define JOY_START   1000
.define JOY_STARTH    10

; OAM
.define OAML_SIZE   0200
.define OAM_SIZE    0220

.define SPC_ROM_SIZE 0002
