.define STACK_TOP 1fff

; assets
.define BG1_TILES_SIZE      01a0
.define BG2_TILES_SIZE      02e0
.define SPRITES_TILES_SIZE  0800
.define BG_PALETTES_SIZE      40
.define SPRITES_PALETTES_SIZE 40
.define BG2_MAP_SIZE        0700
.define BG_BUFFER_SIZE      0800
.define BG1_BUFFER_SIZE     1000

; game
.define LEVEL_WIDTH         0046 ; 70
.define LEVEL_HEIGHT        001c ; 28
.define BUFFER_WIDTH        0040 ; 64

; joypad
.define JOY_A       0080
.define JOY_AL        80
.define JOY_START   1000
.define JOY_STARTH    10

; OAM
.define OAML_SIZE   0200
.define OAM_SIZE    0220

.define SPC_ROM_SIZE 0002
