#!/bin/bash

superfamiconv -i bg2.png -p bg2.pal -t bg2.tiles -m bg2.map --out-tiles-image bg2.tiles.png --color-zero 00000000
ruby -I../../SNES_Utils/lib/ ../../SNES_Utils/bin/png2snes -f sprites.png -b 4
ruby -I../../SNES_Utils/lib/ ../../SNES_Utils/bin/png2snes -f bg1.png -b 4

# sprites1.pal -> sprites2.pal
# 0x5b9b -> 0x77bd
# 0x1719 -> 0x6319
# 0x6ffd -> 0x77bd
# 0x213c -> 0x6319
# 0x121b -> 0x6319
